# Generated by Django 4.1.7 on 2023-04-09 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_general", models.IntegerField(unique=True)),
                ("descripcion", models.CharField(max_length=30)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("HERRAMIENTA", "Herramienta"), ("INSUMO", "Insumo")],
                        max_length=30,
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date(2023, 4, 9))),
            ],
        ),
        migrations.CreateModel(
            name="Subelemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=1)),
                ("codigo_unico", models.IntegerField()),
                ("marca", models.CharField(max_length=30)),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.elemento",
                    ),
                ),
            ],
        ),
    ]
