# Generated by Django 4.2 on 2023-10-20 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_elemento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 10, 20)),
        ),
    ]
