# Generated by Django 4.1.7 on 2023-03-31 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "fecha",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 3, 31, 14, 50, 57, 951277)
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "objeto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="general_usage.objeto",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            bases=("general_usage.objeto",),
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "objeto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="general_usage.objeto",
                    ),
                ),
                ("contenido", models.CharField(max_length=255)),
            ],
            bases=("general_usage.objeto",),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "objeto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="general_usage.objeto",
                    ),
                ),
                ("cantidad_pedida", models.IntegerField(default=1)),
                (
                    "subelemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.subelemento",
                    ),
                ),
            ],
            bases=("general_usage.objeto",),
        ),
        migrations.AddIndex(
            model_name="objeto",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="general_usa_content_497822_idx",
            ),
        ),
    ]
