# Generated by Django 4.2 on 2023-04-14 16:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_usage.objeto')),
                ('nombre', models.CharField(max_length=255)),
            ],
            bases=('general_usage.objeto',),
        ),
        migrations.CreateModel(
            name='Grupo_Pedido',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_usage.objeto')),
                ('estado', models.CharField(choices=[('EN PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN PROCESO', max_length=30)),
            ],
            bases=('general_usage.objeto',),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_usage.objeto')),
                ('contenido', models.CharField(max_length=255)),
            ],
            bases=('general_usage.objeto',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEDIDO', 'Pedido'), ('DESPACHADO', 'DESPACHADO')], default='PEDIDO', max_length=30)),
                ('cantidad_pedida', models.IntegerField(default=1)),
                ('cantidad_enviada', models.IntegerField(default=0)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elemento')),
                ('subelemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.subelemento')),
                ('grupo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_usage.grupo_pedido')),
            ],
        ),
        migrations.AddIndex(
            model_name='objeto',
            index=models.Index(fields=['content_type', 'object_id'], name='general_usa_content_497822_idx'),
        ),
    ]
