# Generated by Django 4.1.7 on 2023-04-09 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
