# Generated by Django 4.1.7 on 2023-04-03 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 20, 49, 2, 540987)
            ),
        ),
    ]
