# Generated by Django 4.1.7 on 2023-04-03 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0002_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo_pedido",
            name="estado",
            field=models.CharField(
                choices=[("EN PROCESO", "En proceso"), ("FINALIZADA", "Finalizada")],
                default="EN PROCESO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 22, 9, 10, 422560)
            ),
        ),
    ]
