# Generated by Django 4.1.7 on 2023-03-31 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0002_objeto_usuario_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivo",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 31, 15, 19, 47, 687195)
            ),
        ),
    ]
