# Generated by Django 4.1.7 on 2023-03-31 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0003_alter_archivo_nombre_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 31, 16, 9, 39, 1836)
            ),
        ),
    ]
