# Generated by Django 4.1.7 on 2023-04-03 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0003_grupo_pedido_estado_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cantidad_enviada",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[("PEDIDO", "Pedido"), ("DESPACHADO", "DESPACHADO")],
                default="PEDIDO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="grupo_pedido",
            name="estado",
            field=models.CharField(
                choices=[("EN PROCESO", "En proceso"), ("FINALIZADO", "Finalizado")],
                default="EN PROCESO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 22, 48, 47, 103512)
            ),
        ),
    ]
