# Generated by Django 4.1.7 on 2023-04-02 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0005_pedido_elemento_alter_objeto_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="elemento",
        ),
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 3, 33, 46, 655932)
            ),
        ),
    ]
