# Generated by Django 4.1.7 on 2023-04-02 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0006_remove_pedido_elemento_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 3, 42, 22, 517068)
            ),
        ),
    ]
