# Generated by Django 4.1.7 on 2023-04-02 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_usage", "0009_alter_objeto_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 13, 41, 553820)
            ),
        ),
    ]
