# Generated by Django 4.2 on 2023-04-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="apartamentos",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="administrador",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="estado",
            field=models.CharField(
                choices=[("INACTIVO", "Inactivo"), ("POTENCIAL", "Potencial")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="supervisor",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono_supervisor",
            field=models.CharField(max_length=30),
        ),
    ]
