# Generated by Django 4.2 on 2023-08-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_empleado_organisation'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
