# Generated by Django 4.1.7 on 2023-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mensajes",
            field=models.BooleanField(default=False),
        ),
    ]
