# Generated by Django 4.1.7 on 2023-03-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="administrador",
            field=models.CharField(default="test1", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono",
            field=models.IntegerField(default=26352323),
            preserve_default=False,
        ),
    ]
