# Generated by Django 4.2 on 2023-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_orgnanizacion',
            new_name='nombre_organizacion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_servicio',
            field=models.CharField(blank=True, choices=[('VENCIDO', 'Vencido'), ('GARANTIA', 'Garantia'), ('EN TERMINOS', 'En terminos')], max_length=15),
        ),
    ]
