# Generated by Django 4.2 on 2023-04-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_cliente_apartamentos_alter_cliente_administrador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre_orgnanizacion",
            field=models.CharField(max_length=150),
        ),
    ]
