# Generated by Django 4.2 on 2023-08-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_nombre_orgnanizacion_cliente_nombre_organizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='organisation',
        ),
    ]
