# Generated by Django 4.1.5 on 2023-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_llamada"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="carpeta",
            field=models.CharField(default="/home/anorak/Test/", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visita",
            name="estado",
            field=models.CharField(
                choices=[("FINALIZADA", "Finalizada"), ("EN PROCESO", "En proceso")],
                default="EN PROCESO",
                max_length=15,
            ),
        ),
    ]
