# Generated by Django 4.1.5 on 2023-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_remove_cliente_administrador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="frecuencia_meses",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ultima_visita",
            field=models.DateField(null=True),
        ),
    ]
