# Generated by Django 4.1.7 on 2023-04-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_user_mensajes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_organisor",
            field=models.BooleanField(default=False),
        ),
    ]
