# Generated by Django 4.1.7 on 2023-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_cliente_administrador_cliente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
