# Generated by Django 4.1.7 on 2023-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_alter_cliente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nit",
            field=models.CharField(max_length=15),
        ),
    ]
