# Generated by Django 4.1.7 on 2023-04-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_alter_user_is_organisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="correo_supervisor",
            field=models.EmailField(default="correo@test.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="supervisor",
            field=models.CharField(default="test", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono_supervisor",
            field=models.CharField(default="126126512", max_length=15),
            preserve_default=False,
        ),
    ]
