# Generated by Django 4.1.5 on 2023-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_carpeta_alter_visita_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="visita",
            name="carpeta",
            field=models.CharField(default="2023", max_length=30),
            preserve_default=False,
        ),
    ]
