# Generated by Django 4.1.5 on 2023-03-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0004_visita_carpeta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llamada",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="estado",
        ),
        migrations.AddField(
            model_name="interaccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("FINALIZADA", "Finalizada"),
                    ("EN PROCESO", "En proceso"),
                    ("PENDIENTE", "Pendiente"),
                ],
                default="EN PROCESO",
                max_length=15,
            ),
        ),
    ]
