# Generated by Django 4.1.5 on 2023-02-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_remove_visita_n_pisos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="proxima_visita",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="ultima_visita",
        ),
    ]
