# Generated by Django 4.1.5 on 2023-02-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_remove_cliente_proxima_visita_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visita",
        ),
    ]
