# Generated by Django 4.1.5 on 2023-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0010_user_is_agent_user_is_organisor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_agent",
            new_name="fachadas",
        ),
        migrations.AddField(
            model_name="user",
            name="fumigacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="inventario",
            field=models.BooleanField(default=False),
        ),
    ]
