# Generated by Django 4.1.5 on 2023-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0012_visita"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="fecha_vencimiento",
            field=models.DateField(null=True),
        ),
    ]
