# Generated by Django 4.1.5 on 2023-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0013_cliente_fecha_vencimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="email",
            field=models.EmailField(default="test@test.com", max_length=254),
            preserve_default=False,
        ),
    ]
