# Generated by Django 4.1.5 on 2023-02-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0015_cliente_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
