# Generated by Django 4.1.5 on 2023-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0016_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="email",
        ),
    ]
