# Generated by Django 4.1.5 on 2023-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0017_remove_empleado_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="visita",
            name="estado",
            field=models.CharField(
                choices=[("FINALIZADA", "Finalizada"), ("EN PROCESO", "En proceso")],
                default="EN PROCESO",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="estado",
            field=models.CharField(
                choices=[("INACTIVO", "Inactivo"), ("POTENCIAL", "Potencial")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_vencimiento",
            field=models.DateField(default=None, null=True),
        ),
    ]
