# Generated by Django 4.1.5 on 2023-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0018_visita_estado_alter_cliente_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="rechazos",
            field=models.IntegerField(default=0),
        ),
    ]
