# Generated by Django 4.1.7 on 2023-04-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("general_usage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "lista_clientes",
                    models.CharField(
                        choices=[
                            ("INACTIVO", "Inactivo"),
                            ("ACTIVO", "Activo"),
                            ("POTENCIAL", "Potencial"),
                            ("TODOS", "Todos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "imagen",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general_usage.archivo",
                    ),
                ),
            ],
        ),
    ]
