# Generated by Django 4.1.7 on 2023-04-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajes_masivos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="estado",
            field=models.CharField(default="PENDIENTE", max_length=30),
        ),
    ]
