# Generated by Django 4.1.5 on 2023-03-20 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0005_remove_llamada_estado_remove_visita_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_obra", models.CharField(max_length=30)),
                ("direccion", models.CharField(max_length=30)),
                ("nit", models.IntegerField()),
                ("administrador", models.CharField(max_length=30)),
                ("numero_tel", models.IntegerField(max_length=10)),
                ("correo", models.EmailField(max_length=254, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN PROCESO", "En proceso"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        max_length=10,
                    ),
                ),
                ("carpeta", models.CharField(max_length=30)),
                ("fecha_inicio", models.DateField(default=datetime.date(2023, 3, 20))),
                (
                    "empleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.empleado",
                    ),
                ),
            ],
        ),
    ]
