# Generated by Django 4.1.5 on 2023-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fachadas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="numero_tel",
            field=models.IntegerField(),
        ),
    ]
