# Generated by Django 4.1.5 on 2023-03-20 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fachadas", "0002_alter_obra_numero_tel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obra",
            name="carpeta",
        ),
    ]
