# Generated by Django 4.1.5 on 2023-03-21 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fachadas", "0003_remove_obra_carpeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="fecha_inicio",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "cargo",
                    models.CharField(
                        choices=[("SUPERVISOR", "Supervisor"), ("OBRERO", "Obrero")],
                        max_length=30,
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fachadas.obra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=30)),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("precio_unidad", models.FloatField()),
                ("cobro_unidad", models.FloatField()),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fachadas.obra"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "costo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fachadas.costo",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fachadas.trabajador",
                    ),
                ),
            ],
            bases=("fachadas.costo",),
        ),
    ]
