# Generated by Django 4.1.5 on 2023-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fachadas", "0005_trabajador_acumulado"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="fecha_ultimo_pago",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="ultimo_pago",
            field=models.FloatField(default=0),
        ),
    ]
