# Generated by Django 4.1.5 on 2023-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fachadas", "0006_trabajador_fecha_ultimo_pago_trabajador_ultimo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="costo_total",
            field=models.FloatField(default=0),
        ),
    ]
